import { Restaurant, Category, MenuItem } from '@/types/database';

// Fixed demo restaurant data - used for public demo menu view
export const DEMO_RESTAURANT: Restaurant = {
  id: 'demo-restaurant-id',
  owner_id: null,
  slug: 'demo-doener-palace',
  name: 'Demo Döner Palace',
  address: 'Musterstraße 1, 65549 Limburg',
  phone: null,
  whatsapp_number: null,
  opening_hours: {
    mo: { open: '11:00', close: '22:00' },
    di: { open: '11:00', close: '22:00' },
    mi: { open: '11:00', close: '22:00' },
    do: { open: '11:00', close: '22:00' },
    fr: { open: '11:00', close: '23:00' },
    sa: { open: '12:00', close: '23:00' },
    so: { open: '12:00', close: '21:00' },
  },
  theme: 'classic',
  menu_language: 'de',
  logo_url: null,
  is_active: true,
  is_demo: true,
  auto_images: true,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};

export const DEMO_CATEGORIES: Category[] = [
  {
    id: 'demo-cat-doener',
    restaurant_id: DEMO_RESTAURANT.id,
    name: 'Döner & Wraps',
    position: 0,
    created_at: new Date().toISOString(),
  },
  {
    id: 'demo-cat-beilagen',
    restaurant_id: DEMO_RESTAURANT.id,
    name: 'Beilagen',
    position: 1,
    created_at: new Date().toISOString(),
  },
  {
    id: 'demo-cat-getraenke',
    restaurant_id: DEMO_RESTAURANT.id,
    name: 'Getränke',
    position: 2,
    created_at: new Date().toISOString(),
  },
];

export const DEMO_MENU_ITEMS: MenuItem[] = [
  // Döner & Wraps
  {
    id: 'demo-item-1',
    category_id: 'demo-cat-doener',
    name: 'Döner im Brot',
    description: 'Mit frischem Salat, Tomaten, Zwiebeln und Soße nach Wahl',
    price: 5.50,
    image_url: null,
    image_mode: 'auto',
    image_library_key: null,
    is_available: true,
    is_vegetarian: false,
    is_vegan: false,
    is_popular: true,
    is_special: false,
    position: 0,
    allergens: ['gluten', 'sesame'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'demo-item-2',
    category_id: 'demo-cat-doener',
    name: 'Döner Teller',
    description: 'Mit Reis oder Pommes, Salat und Soße',
    price: 9.50,
    image_url: null,
    image_mode: 'auto',
    image_library_key: null,
    is_available: true,
    is_vegetarian: false,
    is_vegan: false,
    is_popular: false,
    is_special: true,
    position: 1,
    allergens: ['gluten'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'demo-item-3',
    category_id: 'demo-cat-doener',
    name: 'Dürüm',
    description: 'Döner im Wrap mit Salat und Soße',
    price: 6.50,
    image_url: null,
    image_mode: 'auto',
    image_library_key: null,
    is_available: true,
    is_vegetarian: false,
    is_vegan: false,
    is_popular: false,
    is_special: false,
    position: 2,
    allergens: ['gluten', 'sesame'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'demo-item-4',
    category_id: 'demo-cat-doener',
    name: 'Vegetarischer Döner',
    description: 'Mit Falafel, frischem Salat und Hummus',
    price: 5.50,
    image_url: null,
    image_mode: 'auto',
    image_library_key: null,
    is_available: true,
    is_vegetarian: true,
    is_vegan: true,
    is_popular: false,
    is_special: false,
    position: 3,
    allergens: ['gluten', 'sesame'],
    created_at: new Date().toISOString(),
  },
  // Beilagen
  {
    id: 'demo-item-5',
    category_id: 'demo-cat-beilagen',
    name: 'Pommes',
    description: 'Knusprige Pommes Frites',
    price: 3.00,
    image_url: null,
    image_mode: 'auto',
    image_library_key: null,
    is_available: true,
    is_vegetarian: true,
    is_vegan: true,
    is_popular: false,
    is_special: false,
    position: 0,
    allergens: [],
    created_at: new Date().toISOString(),
  },
  {
    id: 'demo-item-6',
    category_id: 'demo-cat-beilagen',
    name: 'Salat',
    description: 'Gemischter Salat mit Dressing',
    price: 4.00,
    image_url: null,
    image_mode: 'auto',
    image_library_key: null,
    is_available: true,
    is_vegetarian: true,
    is_vegan: true,
    is_popular: false,
    is_special: false,
    position: 1,
    allergens: [],
    created_at: new Date().toISOString(),
  },
  {
    id: 'demo-item-7',
    category_id: 'demo-cat-beilagen',
    name: 'Falafel (3 Stück)',
    description: 'Hausgemachte Falafel mit Hummus',
    price: 3.50,
    image_url: null,
    image_mode: 'auto',
    image_library_key: null,
    is_available: true,
    is_vegetarian: true,
    is_vegan: true,
    is_popular: true,
    is_special: false,
    position: 2,
    allergens: ['sesame'],
    created_at: new Date().toISOString(),
  },
  // Getränke
  {
    id: 'demo-item-8',
    category_id: 'demo-cat-getraenke',
    name: 'Cola',
    description: '0,33l',
    price: 2.50,
    image_url: null,
    image_mode: 'auto',
    image_library_key: null,
    is_available: true,
    is_vegetarian: true,
    is_vegan: true,
    is_popular: false,
    is_special: false,
    position: 0,
    allergens: [],
    created_at: new Date().toISOString(),
  },
  {
    id: 'demo-item-9',
    category_id: 'demo-cat-getraenke',
    name: 'Fanta',
    description: '0,33l',
    price: 2.50,
    image_url: null,
    image_mode: 'auto',
    image_library_key: null,
    is_available: true,
    is_vegetarian: true,
    is_vegan: true,
    is_popular: false,
    is_special: false,
    position: 1,
    allergens: [],
    created_at: new Date().toISOString(),
  },
  {
    id: 'demo-item-10',
    category_id: 'demo-cat-getraenke',
    name: 'Ayran',
    description: 'Türkisches Joghurtgetränk',
    price: 2.00,
    image_url: null,
    image_mode: 'auto',
    image_library_key: null,
    is_available: true,
    is_vegetarian: true,
    is_vegan: false,
    is_popular: false,
    is_special: false,
    position: 2,
    allergens: ['milk'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'demo-item-11',
    category_id: 'demo-cat-getraenke',
    name: 'Wasser',
    description: '0,5l still oder sprudelnd',
    price: 2.00,
    image_url: null,
    image_mode: 'auto',
    image_library_key: null,
    is_available: true,
    is_vegetarian: true,
    is_vegan: true,
    is_popular: false,
    is_special: false,
    position: 3,
    allergens: [],
    created_at: new Date().toISOString(),
  },
];

// Get all demo data as a bundle
export function getDemoData() {
  return {
    restaurant: DEMO_RESTAURANT,
    categories: DEMO_CATEGORIES,
    menuItems: DEMO_MENU_ITEMS,
  };
}
