/**
 * Emoji-based Image Library for Menu Items
 *
 * This library provides emoji representations for menu items when
 * no custom image is available. Contains 300+ entries with fuzzy matching.
 */

export const imageLibrary: Record<string, string> = {

  // ==================== FRÜHSTÜCK ====================
  'kleines frühstück': '🥐🍳',
  'großes frühstück': '🍳🥓🥐',
  'veganes frühstück': '🥗🍞',
  'englisches frühstück': '🍳🥓🫘',
  'amerikanisches frühstück': '🥞🥓🍳',
  'continental frühstück': '🥐☕',
  'rührei': '🍳',
  'spiegelei': '🍳',
  'omelette': '🥚🧀',
  'omelett': '🥚🧀',
  'käse omelette': '🥚🧀',
  'schinken omelette': '🥚🥓',
  'müsli': '🥣',
  'muesli': '🥣',
  'joghurt': '🥛',
  'joghurt mit früchten': '🥛🍓',
  'pancakes': '🥞',
  'pancake': '🥞',
  'pfannkuchen': '🥞',
  'waffeln': '🧇',
  'waffel': '🧇',
  'french toast': '🍞🍯',
  'arme ritter': '🍞🍯',
  'porridge': '🥣',
  'haferbrei': '🥣',
  'açai bowl': '🫐🥣',
  'acai bowl': '🫐🥣',

  // ==================== BRÖTCHEN / SANDWICHES ====================
  'brötchen': '🥖',
  'semmel': '🥖',
  'belegtes brötchen': '🥪',
  'schinken brötchen': '🥪🥓',
  'schinken-käse': '🥪🧀🥓',
  'käse brötchen': '🥪🧀',
  'lachs brötchen': '🥪🐟',
  'lachs': '🐟',
  'thunfisch brötchen': '🥪🐟',
  'thunfisch': '🐟',
  'vegetarisch': '🥬🥪',
  'vegetarisches brötchen': '🥬🥪',
  'sandwich': '🥪',
  'club sandwich': '🥪🥓',
  'toast': '🍞',
  'käse toast': '🍞🧀',
  'schinken-käse toast': '🍞🧀🥓',
  'baguette': '🥖',
  'ciabatta': '🥖',
  'wrap': '🌯',
  'chicken wrap': '🌯🍗',
  'veggie wrap': '🌯🥬',
  'falafel wrap': '🌯🧆',
  'bagel': '🥯',
  'croissant': '🥐',
  'schoko-croissant': '🥐🍫',
  'pain au chocolat': '🥐🍫',

  // ==================== KUCHEN & GEBÄCK ====================
  'kuchen': '🍰',
  'torte': '🎂',
  'apfelkuchen': '🍎🥧',
  'apple pie': '🍎🥧',
  'käsekuchen': '🍰🧀',
  'cheesecake': '🍰🧀',
  'schwarzwälder': '🍫🍒🎂',
  'schwarzwälder kirsch': '🍫🍒🎂',
  'brownie': '🍫🟫',
  'schoko brownie': '🍫🟫',
  'muffin': '🧁',
  'schoko-muffin': '🧁🍫',
  'blaubeer muffin': '🧁🫐',
  'donut': '🍩',
  'schoko donut': '🍩🍫',
  'cookie': '🍪',
  'cookies': '🍪',
  'schoko cookie': '🍪🍫',
  'tiramisu': '🍰☕',
  'panna cotta': '🍮',
  'crème brûlée': '🍮🔥',
  'creme brulee': '🍮🔥',
  'eis': '🍨',
  'eiscreme': '🍨',
  'vanilleeis': '🍨',
  'schokoeis': '🍫🍨',
  'erdbeereis': '🍓🍨',
  'waffel mit eis': '🧇🍨',
  'obstsalat': '🍓🍇🥭',
  'baklava': '🍯🥜',
  'künefe': '🧀🍯',
  'kunefe': '🧀🍯',
  'lokum': '🍬',
  'churros': '🍩🍫',

  // ==================== KAFFEE & HEISSGETRÄNKE ====================
  'kaffee': '☕',
  'filterkaffee': '☕',
  'espresso': '☕',
  'doppio': '☕☕',
  'cappuccino': '☕🥛',
  'latte': '🥛☕',
  'latte macchiato': '🥛☕',
  'flat white': '☕🥛',
  'americano': '☕💧',
  'mokka': '☕🍫',
  'mocha': '☕🍫',
  'macchiato': '☕🥛',
  'cortado': '☕🥛',
  'affogato': '☕🍨',
  'irish coffee': '☕🥃',
  'eiskaffee': '🧊☕',
  'frappuccino': '🧊☕🥛',
  'tee': '🍵',
  'schwarztee': '🍵',
  'grüner tee': '🍵🌿',
  'pfefferminztee': '🍵🌿',
  'kamillentee': '🍵🌼',
  'früchtetee': '🍵🍓',
  'chai': '🍵🧡',
  'chai latte': '🍵🥛',
  'matcha': '🍵💚',
  'matcha latte': '🍵💚🥛',
  'heiße schokolade': '🍫☕',
  'heisse schokolade': '🍫☕',
  'kakao': '🍫☕',
  'hot chocolate': '🍫☕',

  // ==================== SHAKES & SMOOTHIES ====================
  'shake': '🥤',
  'milkshake': '🥤🥛',
  'milch shake': '🥤🥛',
  'schoko shake': '🥤🍫',
  'schokoshake': '🥤🍫',
  'schokoladen shake': '🥤🍫',
  'chocolate shake': '🥤🍫',
  'vanille shake': '🥤🍦',
  'vanilleshake': '🥤🍦',
  'vanilla shake': '🥤🍦',
  'erdbeer shake': '🥤🍓',
  'erdbeershake': '🥤🍓',
  'strawberry shake': '🥤🍓',
  'bananen shake': '🥤🍌',
  'bananenshake': '🥤🍌',
  'banana shake': '🥤🍌',
  'oreo shake': '🥤🍪',
  'oreoshake': '🥤🍪',
  'cookies and cream': '🥤🍪',
  'karamell shake': '🥤🍯',
  'karamellshake': '🥤🍯',
  'caramel shake': '🥤🍯',
  'erdnuss shake': '🥤🥜',
  'peanut butter shake': '🥤🥜',
  'mango shake': '🥤🥭',
  'smoothie': '🥤🍓',
  'grüner smoothie': '🥤🥬',
  'green smoothie': '🥤🥬',
  'beeren smoothie': '🥤🫐',
  'berry smoothie': '🥤🫐',
  'mango smoothie': '🥤🥭',
  'tropical smoothie': '🥤🍍',
  'acai smoothie': '🥤🫐',
  'protein shake': '🥤💪',

  // ==================== BURGER ====================
  'burger': '🍔',
  'hamburger': '🍔',
  'classic burger': '🍔',
  'klassischer burger': '🍔',
  'cheeseburger': '🍔🧀',
  'cheese burger': '🍔🧀',
  'double cheeseburger': '🍔🍔🧀',
  'bacon burger': '🍔🥓',
  'bacon cheeseburger': '🍔🥓🧀',
  'bbq burger': '🍔🍖',
  'bbq bacon burger': '🍔🥓🍖',
  'mushroom burger': '🍔🍄',
  'pilz burger': '🍔🍄',
  'veggie burger': '🍔🥬',
  'vegetarischer burger': '🍔🥬',
  'vegan burger': '🍔🌱',
  'beyond burger': '🍔🌱',
  'impossible burger': '🍔🌱',
  'chicken burger': '🍔🍗',
  'crispy chicken burger': '🍔🍗',
  'fish burger': '🍔🐟',
  'fisch burger': '🍔🐟',
  'double burger': '🍔🍔',
  'triple burger': '🍔🍔🍔',
  'pulled pork burger': '🍔🐷',
  'jalapeño burger': '🍔🌶️',
  'spicy burger': '🍔🌶️',
  'texas burger': '🍔🤠',
  'swiss burger': '🍔🧀',
  'blue cheese burger': '🍔🧀',
  'avocado burger': '🍔🥑',
  'hawaii burger': '🍔🍍',

  // ==================== DÖNER & TÜRKISCH ====================
  'döner': '🥙',
  'doner': '🥙',
  'döner kebab': '🥙',
  'döner im brot': '🥙🍞',
  'döner im fladenbrot': '🥙🍞',
  'döner teller': '🥙🍽️',
  'döner box': '🥙📦',
  'dürüm': '🌯',
  'dürum': '🌯',
  'durum': '🌯',
  'yufka': '🌯',
  'lahmacun': '🫓🥩',
  'türkische pizza': '🫓🥩',
  'pide': '🫓',
  'pide mit käse': '🫓🧀',
  'pide mit hackfleisch': '🫓🥩',
  'köfte': '🧆',
  'kofte': '🧆',
  'köfte teller': '🧆🍽️',
  'adana': '🍢',
  'adana kebab': '🍢',
  'adana teller': '🍢🍽️',
  'iskender': '🥙🍅',
  'iskender kebab': '🥙🍅',
  'falafel': '🧆',
  'falafel teller': '🧆🍽️',
  'falafel sandwich': '🧆🥪',
  'hummus': '🫘',
  'hummus teller': '🫘🍽️',
  'börek': '🥟',
  'borek': '🥟',
  'sigara börek': '🥟',
  'su börek': '🥟',
  'gözleme': '🫓',
  'gozleme': '🫓',
  'ayran': '🥛',
  'cacık': '🥒🥛',
  'tzatziki': '🥒🥛',
  'tavuk': '🍗',
  'tavuk döner': '🍗🥙',
  'hähnchen döner': '🍗🥙',
  'chicken döner': '🍗🥙',

  // ==================== PIZZA ====================
  'pizza': '🍕',
  'pizza margherita': '🍕🍅',
  'margherita': '🍕🍅',
  'pizza salami': '🍕🥓',
  'salami pizza': '🍕🥓',
  'pepperoni pizza': '🍕🥓',
  'pizza schinken': '🍕🥓',
  'schinken pizza': '🍕🥓',
  'pizza prosciutto': '🍕🥓',
  'pizza funghi': '🍕🍄',
  'pilz pizza': '🍕🍄',
  'mushroom pizza': '🍕🍄',
  'pizza hawaii': '🍕🍍',
  'hawaii pizza': '🍕🍍',
  'pizza tonno': '🍕🐟',
  'thunfisch pizza': '🍕🐟',
  'pizza quattro stagioni': '🍕🍄🥓',
  'vier jahreszeiten': '🍕🍄🥓',
  'pizza quattro formaggi': '🍕🧀🧀',
  'vier käse': '🍕🧀🧀',
  'pizza vegetarisch': '🍕🥬',
  'vegetarische pizza': '🍕🥬',
  'veggie pizza': '🍕🥬',
  'pizza diavola': '🍕🌶️',
  'scharfe pizza': '🍕🌶️',
  'pizza capricciosa': '🍕🍄🥓',
  'pizza marinara': '🍕🧄',
  'pizza frutti di mare': '🍕🦐',
  'meeresfrüchte pizza': '🍕🦐',
  'calzone': '🥟🍕',
  'pizza calzone': '🥟🍕',
  'pizza bbq': '🍕🍖',
  'bbq chicken pizza': '🍕🍗🍖',
  'pizza spinat': '🍕🥬',
  'spinach pizza': '🍕🥬',
  'pizza speciale': '🍕⭐',

  // ==================== PASTA ====================
  'pasta': '🍝',
  'nudeln': '🍝',
  'spaghetti': '🍝',
  'spaghetti bolognese': '🍝🥩',
  'bolognese': '🍝🥩',
  'bolo': '🍝🥩',
  'spaghetti carbonara': '🍝🥓🥚',
  'carbonara': '🍝🥓🥚',
  'spaghetti napoli': '🍝🍅',
  'napoli': '🍝🍅',
  'spaghetti aglio olio': '🍝🧄',
  'aglio olio': '🍝🧄',
  'penne': '🍝',
  'penne arrabiata': '🍝🌶️',
  'arrabiata': '🍝🌶️',
  'arrabbiata': '🍝🌶️',
  'penne al forno': '🍝🧀',
  'rigatoni': '🍝',
  'tagliatelle': '🍝',
  'fettuccine': '🍝',
  'fettuccine alfredo': '🍝🧀🥛',
  'alfredo': '🍝🧀🥛',
  'lasagne': '🍝🧀🥩',
  'lasagna': '🍝🧀🥩',
  'ravioli': '🥟🍝',
  'tortellini': '🥟🍝',
  'gnocchi': '🥔🍝',
  'risotto': '🍚',
  'risotto pilze': '🍚🍄',
  'risotto meeresfrüchte': '🍚🦐',
  'mac and cheese': '🍝🧀',
  'käsespätzle': '🍝🧀',
  'spätzle': '🍝',

  // ==================== SALATE ====================
  'salat': '🥗',
  'gemischter salat': '🥗',
  'mixed salad': '🥗',
  'beilagensalat': '🥗',
  'caesar salat': '🥗🧀🍗',
  'caesar salad': '🥗🧀🍗',
  'cäsar salat': '🥗🧀🍗',
  'chicken caesar': '🥗🍗',
  'griechischer salat': '🥗🧀🫒',
  'greek salad': '🥗🧀🫒',
  'bauernsalat': '🥗🧀',
  'caprese': '🍅🧀',
  'insalata caprese': '🍅🧀',
  'tomate mozzarella': '🍅🧀',
  'thunfisch salat': '🥗🐟',
  'tuna salad': '🥗🐟',
  'hähnchen salat': '🥗🍗',
  'hühnchen salat': '🥗🍗',
  'chicken salad': '🥗🍗',
  'quinoa salat': '🥗',
  'couscous salat': '🥗',
  'nudelsalat': '🥗🍝',
  'kartoffelsalat': '🥗🥔',
  'krautsalat': '🥗🥬',
  'coleslaw': '🥗🥬',
  'rucola salat': '🥗🌿',
  'fitness salat': '🥗💪',

  // ==================== SUPPEN ====================
  'suppe': '🍲',
  'soup': '🍲',
  'tagessuppe': '🍲',
  'tomatensuppe': '🍲🍅',
  'tomato soup': '🍲🍅',
  'kürbissuppe': '🍲🎃',
  'pumpkin soup': '🍲🎃',
  'gulaschsuppe': '🍲🥩',
  'goulash soup': '🍲🥩',
  'hühnersuppe': '🍲🍗',
  'chicken soup': '🍲🍗',
  'nudelsuppe': '🍲🍜',
  'noodle soup': '🍲🍜',
  'zwiebelsuppe': '🍲🧅',
  'onion soup': '🍲🧅',
  'french onion soup': '🍲🧅🧀',
  'gemüsesuppe': '🍲🥬',
  'vegetable soup': '🍲🥬',
  'kartoffelsuppe': '🍲🥔',
  'linsensuppe': '🍲🫘',
  'mercimek': '🍲🫘',
  'minestrone': '🍲🥬',
  'miso suppe': '🍲🇯🇵',
  'pho': '🍲🍜🇻🇳',
  'ramen': '🍜🍥',
  'thai suppe': '🍲🌶️',

  // ==================== POMMES & BEILAGEN ====================
  'pommes': '🍟',
  'pommes frites': '🍟',
  'french fries': '🍟',
  'fries': '🍟',
  'fritten': '🍟',
  'süßkartoffel pommes': '🍠🍟',
  'sweet potato fries': '🍠🍟',
  'curly fries': '🍟🌀',
  'twister fries': '🍟🌀',
  'wedges': '🥔',
  'potato wedges': '🥔',
  'kartoffelecken': '🥔',
  'onion rings': '🧅🍟',
  'zwiebelringe': '🧅🍟',
  'nuggets': '🍗',
  'chicken nuggets': '🍗',
  'chicken strips': '🍗',
  'chicken fingers': '🍗',
  'chicken tenders': '🍗',
  'chicken wings': '🍗🔥',
  'wings': '🍗🔥',
  'hot wings': '🍗🔥🌶️',
  'buffalo wings': '🍗🔥',
  'mozzarella sticks': '🧀',
  'cheese sticks': '🧀',
  'käsesticks': '🧀',
  'jalapeño poppers': '🌶️🧀',
  'nachos': '🌮🧀',
  'nachos mit käse': '🌮🧀',
  'loaded nachos': '🌮🧀🥩',
  'reis': '🍚',
  'rice': '🍚',
  'basmati': '🍚',
  'gebratener reis': '🍚🥢',
  'fried rice': '🍚🥢',
  'kartoffelpüree': '🥔',
  'kartoffelpuree': '🥔',
  'mashed potatoes': '🥔',
  'stampfkartoffeln': '🥔',
  'bratkartoffeln': '🥔🍳',
  'ofenkartoffel': '🥔',
  'baked potato': '🥔',
  'kroketten': '🥔',
  'rösti': '🥔',
  'knoblauchbrot': '🍞🧄',
  'garlic bread': '🍞🧄',
  'aioli': '🧄',
  'gemüse': '🥬',
  'grillgemüse': '🥬🔥',
  'couscous': '🥣',

  // ==================== GETRÄNKE ====================
  'wasser': '💧',
  'water': '💧',
  'mineralwasser': '💧✨',
  'sparkling water': '💧✨',
  'stilles wasser': '💧',
  'still water': '💧',
  'cola': '🥤🟤',
  'coca cola': '🥤🟤',
  'pepsi': '🥤🟤',
  'fanta': '🥤🟠',
  'sprite': '🥤💚',
  'mezzo mix': '🥤🟤🟠',
  'apfelschorle': '🥤🍎',
  'apple spritzer': '🥤🍎',
  'orangensaft': '🥤🍊',
  'orange juice': '🥤🍊',
  'o-saft': '🥤🍊',
  'osaft': '🥤🍊',
  'apfelsaft': '🥤🍎',
  'apple juice': '🥤🍎',
  'limonade': '🥤🍋',
  'lemonade': '🥤🍋',
  'zitronenlimonade': '🥤🍋',
  'eistee': '🥤🍵',
  'iced tea': '🥤🍵',
  'ice tea': '🥤🍵',
  'eistee pfirsich': '🥤🍑',
  'eistee zitrone': '🥤🍋',
  'energy drink': '🥤⚡',
  'energy': '🥤⚡',
  'red bull': '🥤⚡',
  'bier': '🍺',
  'beer': '🍺',
  'pils': '🍺',
  'pilsner': '🍺',
  'weizen': '🍺🌾',
  'hefeweizen': '🍺🌾',
  'weißbier': '🍺🌾',
  'weissbier': '🍺🌾',
  'radler': '🍺🍋',
  'shandy': '🍺🍋',
  'alkoholfrei': '🍺🚫',
  'non-alcoholic': '🍺🚫',
  'wein': '🍷',
  'wine': '🍷',
  'rotwein': '🍷🔴',
  'red wine': '🍷🔴',
  'weißwein': '🍷⚪',
  'weisswein': '🍷⚪',
  'white wine': '🍷⚪',
  'rosé': '🍷🌸',
  'rose': '🍷🌸',
  'prosecco': '🥂',
  'sekt': '🥂',
  'champagner': '🥂✨',
  'champagne': '🥂✨',
  'cocktail': '🍹',
  'mojito': '🍹🌿',
  'caipirinha': '🍹🍋',
  'margarita': '🍹🧂',
  'pina colada': '🍹🥥',
  'piña colada': '🍹🥥',
  'long island': '🍹',
  'gin tonic': '🍸',
  'gin & tonic': '🍸',
  'aperol spritz': '🍹🟠',
  'hugo': '🍹🌿',
  'whisky': '🥃',
  'whiskey': '🥃',
  'rum': '🥃',
  'vodka': '🍸',
  'schnaps': '🥃',

  // ==================== ASIATISCH ====================
  'sushi': '🍣',
  'sushi set': '🍣🍱',
  'sashimi': '🍣',
  'maki': '🍣🌀',
  'california roll': '🍣🥑',
  'nigiri': '🍣',
  'temaki': '🍣',
  'miso ramen': '🍜',
  'tonkotsu ramen': '🍜🍖',
  'shoyu ramen': '🍜',
  'pho bo': '🍜🐄',
  'pho ga': '🍜🍗',
  'pad thai': '🍜🥜',
  'curry': '🍛',
  'thai curry': '🍛🌶️',
  'green curry': '🍛💚',
  'red curry': '🍛❤️',
  'massaman curry': '🍛',
  'tikka masala': '🍛🍗',
  'butter chicken': '🍛🍗',
  'korma': '🍛',
  'biryani': '🍚🍗',
  'gebratene nudeln': '🍜🥢',
  'chow mein': '🍜',
  'lo mein': '🍜',
  'bami goreng': '🍜',
  'nasi goreng': '🍚',
  'frühlingsrollen': '🥟',
  'frühlingsrolle': '🥟',
  'spring rolls': '🥟',
  'sommerrollen': '🥟🥬',
  'dim sum': '🥟',
  'gyoza': '🥟',
  'dumplings': '🥟',
  'wonton': '🥟',
  'bao': '🥟',
  'bao bun': '🥟',
  'teriyaki': '🍗🍶',
  'teriyaki chicken': '🍗🍶',
  'teriyaki lachs': '🐟🍶',
  'yakitori': '🍢',
  'satay': '🍢🥜',
  'tofu': '🧈',
  'general tso': '🍗🌶️',
  'kung pao': '🍗🥜🌶️',
  'sweet and sour': '🍗🍋',
  'süß sauer': '🍗🍋',

  // ==================== FLEISCHGERICHTE ====================
  'schnitzel': '🥩🍋',
  'wiener schnitzel': '🥩🍋',
  'jägerschnitzel': '🥩🍄',
  'jaegerschnitzel': '🥩🍄',
  'zigeuner schnitzel': '🥩🫑',
  'cordon bleu': '🥩🧀🥓',
  'steak': '🥩',
  'rumpsteak': '🥩',
  'ribeye': '🥩',
  'filetsteak': '🥩',
  't-bone': '🥩🦴',
  'new york strip': '🥩',
  'entrecote': '🥩',
  'beef': '🐄',
  'rindfleisch': '🐄',
  'rind': '🐄',
  'bratwurst': '🌭',
  'currywurst': '🌭🍛',
  'bockwurst': '🌭',
  'weißwurst': '🌭⚪',
  'hot dog': '🌭',
  'hotdog': '🌭',
  'hähnchen': '🍗',
  'hühnchen': '🍗',
  'chicken': '🍗',
  'grillhähnchen': '🍗🔥',
  'roast chicken': '🍗',
  'hähnchenbrust': '🍗',
  'chicken breast': '🍗',
  'spare ribs': '🍖',
  'spareribs': '🍖',
  'rippchen': '🍖',
  'pulled pork': '🐷',
  'schweinebraten': '🐷',
  'schwein': '🐷',
  'roastbeef': '🥩',
  'lamm': '🐑',
  'lamb': '🐑',
  'lammkoteletts': '🐑🍖',
  'gulasch': '🍲🥩',
  'rinderroulade': '🥩',
  'roulade': '🥩',
  'leberkäse': '🥩',
  'leberkaese': '🥩',

  // ==================== FISCH & MEERESFRÜCHTE ====================
  'fisch': '🐟',
  'fish': '🐟',
  'gegrillter lachs': '🐟🟠🔥',
  'grilled salmon': '🐟🟠🔥',
  'lachsfilet': '🐟🟠',
  'salmon': '🐟🟠',
  'tuna': '🐟',
  'forelle': '🐟',
  'trout': '🐟',
  'kabeljau': '🐟',
  'cod': '🐟',
  'seelachs': '🐟',
  'zander': '🐟',
  'dorade': '🐟',
  'garnelen': '🦐',
  'shrimp': '🦐',
  'prawns': '🦐',
  'gambas': '🦐',
  'scampi': '🦐',
  'calamari': '🦑',
  'tintenfisch': '🦑',
  'squid': '🦑',
  'muscheln': '🦪',
  'mussels': '🦪',
  'miesmuscheln': '🦪',
  'hummer': '🦞',
  'lobster': '🦞',
  'krabben': '🦀',
  'crab': '🦀',
  'fish and chips': '🐟🍟',
  'backfisch': '🐟🍟',
  'fischstäbchen': '🐟',
  'fish fingers': '🐟',

  // ==================== MEXIKANISCH ====================
  'taco': '🌮',
  'tacos': '🌮',
  'chicken tacos': '🌮🍗',
  'beef tacos': '🌮🥩',
  'fish tacos': '🌮🐟',
  'burrito': '🌯',
  'chicken burrito': '🌯🍗',
  'beef burrito': '🌯🥩',
  'quesadilla': '🧀🌮',
  'enchiladas': '🌮🧀',
  'enchilada': '🌮🧀',
  'fajitas': '🌮🫑',
  'fajita': '🌮🫑',
  'guacamole': '🥑',
  'salsa': '🍅🌶️',
  'tortilla': '🫓',
  'chili con carne': '🌶️🥩',
  'chili': '🌶️🥩',
  'burrito bowl': '🥣🌮',

  // ==================== INDISCH ====================
  'naan': '🫓',
  'naan brot': '🫓',
  'papadum': '🫓',
  'samosa': '🥟',
  'pakora': '🍤',
  'tandoori': '🍗🔥',
  'tandoori chicken': '🍗🔥',
  'chicken tikka': '🍗',
  'dal': '🫘',
  'linsen dal': '🫘',
  'paneer': '🧀',
  'palak paneer': '🧀🥬',
  'mango lassi': '🥭🥛',
  'lassi': '🥛',

  // ==================== GRIECHISCH ====================
  'gyros': '🥙',
  'gyros teller': '🥙🍽️',
  'gyrosteller': '🥙🍽️',
  'souvlaki': '🍢',
  'moussaka': '🍆🥩',
  'feta': '🧀',
  'halloumi': '🧀',
  'pita': '🫓',
  'pitabrot': '🫓',
  'dolma': '🥬',
  'dolmades': '🥬',
  'bifteki': '🥩',
  'saganaki': '🧀🔥',

  // ==================== KINDERMENU ====================
  'kindermenu': '🧒🍽️',
  'kindermenü': '🧒🍽️',
  'kids menu': '🧒🍽️',
  'kinder': '🧒',
  'kinderburger': '🧒🍔',
  'kinderpizza': '🧒🍕',
  'kinderpasta': '🧒🍝',
  'kinderschnitzel': '🧒🥩',
  'kindereis': '🧒🍨',
  'für kinder': '🧒',

  // ==================== VEGAN/VEGETARISCH ====================
  'vegan': '🌱',
  'veganer': '🌱',
  'veggie': '🥬',
  'plant based': '🌱',
  'pflanzlich': '🌱',
  'beyond meat': '🌱🍔',
  'impossible': '🌱🍔',
  'tempeh': '🧈',
  'seitan': '🌾',
  'vegetables': '🥬',
  'grilled vegetables': '🥬🔥',
  'gegrilltes gemüse': '🥬🔥',
  'buddha bowl': '🥗🌱',
  'vegane bowl': '🥗🌱',

  // ==================== SNACKS ====================
  'popcorn': '🍿',
  'brezel': '🥨',
  'pretzel': '🥨',
  'laugenbrezel': '🥨',
  'flammkuchen': '🫓🥓',
  'bruschetta': '🍞🍅',
  'antipasti': '🫒🧀',
};

/**
 * Category-based fallback emojis
 */
const categoryFallbacks: Record<string, string> = {
  'frühstück': '🍳',
  'fruehstueck': '🍳',
  'breakfast': '🍳',
  'burger': '🍔',
  'pizza': '🍕',
  'pasta': '🍝',
  'nudeln': '🍝',
  'salat': '🥗',
  'salate': '🥗',
  'salad': '🥗',
  'suppe': '🍲',
  'suppen': '🍲',
  'soup': '🍲',
  'getränke': '🥤',
  'getraenke': '🥤',
  'drinks': '🥤',
  'dessert': '🍰',
  'desserts': '🍰',
  'nachspeise': '🍰',
  'kuchen': '🍰',
  'gebäck': '🥐',
  'gebaeck': '🥐',
  'döner': '🥙',
  'doener': '🥙',
  'kebab': '🥙',
  'türkisch': '🥙',
  'tuerkisch': '🥙',
  'shake': '🥤',
  'shakes': '🥤',
  'smoothie': '🥤',
  'smoothies': '🥤',
  'kaffee': '☕',
  'coffee': '☕',
  'tee': '🍵',
  'beilagen': '🍟',
  'sides': '🍟',
  'extras': '🍟',
  'snacks': '🍿',
  'vorspeisen': '🥗',
  'starters': '🥗',
  'appetizer': '🥗',
  'hauptgerichte': '🍽️',
  'main': '🍽️',
  'hauptgericht': '🍽️',
  'fleisch': '🥩',
  'meat': '🥩',
  'fisch': '🐟',
  'fish': '🐟',
  'meeresfrüchte': '🦐',
  'seafood': '🦐',
  'asiatisch': '🥢',
  'asia': '🥢',
  'asian': '🥢',
  'sushi': '🍣',
  'mexikanisch': '🌮',
  'mexican': '🌮',
  'tex-mex': '🌮',
  'indisch': '🍛',
  'indian': '🍛',
  'griechisch': '🥙',
  'greek': '🥙',
  'italienisch': '🍕',
  'italian': '🍕',
  'brot': '🍞',
  'brötchen': '🥖',
  'broetchen': '🥖',
  'sandwich': '🥪',
  'sandwiches': '🥪',
  'kinder': '🧒🍽️',
  'kids': '🧒🍽️',
  'kindermenu': '🧒🍽️',
  'vegan': '🌱',
  'vegetarisch': '🥬',
  'wein': '🍷',
  'wine': '🍷',
  'bier': '🍺',
  'beer': '🍺',
  'cocktail': '🍹',
  'cocktails': '🍹',
  'alkohol': '🍹',
  'wraps': '🌯',
};

/**
 * Find the best emoji representation for a menu item
 * Uses multiple matching strategies for best results
 */
export function findBestImage(itemName: string, categoryName?: string): string {
  const name = itemName.toLowerCase().trim();
  const category = categoryName?.toLowerCase().trim() || '';

  // 1. Exact match
  if (imageLibrary[name]) {
    return imageLibrary[name];
  }

  // 2. Contains check (longest match first for better specificity)
  const sortedKeys = Object.keys(imageLibrary).sort((a, b) => b.length - a.length);
  for (const key of sortedKeys) {
    if (name.includes(key)) {
      return imageLibrary[key];
    }
  }

  // 3. Reverse contains (key contains name) for short names
  for (const key of sortedKeys) {
    if (key.includes(name) && name.length >= 3) {
      return imageLibrary[key];
    }
  }

  // 4. Word-based matching
  const words = name.split(/[\s\-,\.]+/).filter(w => w.length > 2);
  for (const word of words) {
    if (imageLibrary[word]) {
      return imageLibrary[word];
    }
  }

  // 5. Partial word matching (at least 4 chars)
  for (const word of words) {
    if (word.length >= 4) {
      for (const key of sortedKeys) {
        if (key.includes(word) || word.includes(key)) {
          return imageLibrary[key];
        }
      }
    }
  }

  // 6. Category fallback
  for (const [key, value] of Object.entries(categoryFallbacks)) {
    if (category.includes(key) || name.includes(key)) {
      return value;
    }
  }

  // 7. Generic fallback
  return '🍽️';
}

/**
 * Get emoji for a category name
 */
export function getCategoryEmoji(categoryName: string): string {
  const name = categoryName.toLowerCase().trim();

  for (const [key, value] of Object.entries(categoryFallbacks)) {
    if (name.includes(key) || key.includes(name)) {
      return value;
    }
  }

  return '🍽️';
}
